# Generated by Django 2.2.12 on 2020-09-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='keywords',
            new_name='jkeywords',
        ),
    ]
