# Generated by Django 2.2.12 on 2020-09-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200904_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='jkeywords',
            new_name='keywords',
        ),
    ]
